---
title: "Tarea 5"
output: pdf_document
---

Se realiza un experimento en el que se seleccionan 7 ratones de manera aleatoria
de un total de 16 ratones. A los siete seleccionados se les suministra un 
tratamiento mientras que los restantes formarán el grupo de control. El objetivo
del tratamiento es prolongar la supervivencia de los ratones. La siguiente tabla
muestra el tiempo de supervivencia en días después de suministrar el tratamiento.

Grupo  |     Datos   |     Tamaño de muestra
-------|-------------|---------------------------
Tratamiento | 94, 197, 16, 38, 99, 141, 23 | 7
Control     | 52, 104, 146, 10, 51, 30, 40, 27, 46 | 9

Tu objetivo es determinar si el tratamiento prolongó la supervivencia.

1. Usa las medias de las muestras para determinar si hay 
diferencias en los grupos, esto es calcula $\bar{x}-\bar{y}$.
2. Estima el error estándar de la diferencia usando bootsrap. 
3. Corrobora tus resultados del punto anterior usando que 
$\hat{se}(\bar{x}-\bar{y})=\sqrt{\hat{se}(\bar{x})^2 + \hat{se}(\bar{y})^2}$ 
4. ¿Dirías que el tratamiento incrementó la supervivencia de los ratones?
5. Supongamos que deseamos comparar los grupos usando las medianas en lugar 
de las medias, estima la diferencia de las medias y usa bootsrtap para
estimar el error estándar de la diferencia. ¿Cuál es tu conclusión de los 
resultados?