---
title: "10-Tarea: bootstrap paramétrico"
output: html_document
---

1. Sean $X_1,...,X_n \sim N(\mu, 1)$. Sea $\theta = e^{\mu}$, crea una base de 
datos usando $\mu=5$ que consista de $n=100$ observaciones.

* Usa el método delta para estimar $\hat{se}$ y crea un intervalo del 95% de
confianza. Usa boostrap paramétrico para crear un intervalo del 95%. Usa 
bootstrap no paramétrico para crear un intervalo del 95%. Compara tus respuestas.


* Realiza un histograma de replicaciones bootstrap para cada método, estas son
estimaciones de la distribución de $\hat{\theta}$. El método delta también nos
da una aproximación a esta distribución: $Normal(\hat{\theta},\hat{se}^2)$. 
Comparalos con la verdadera distribución de $\hat{\theta}$ (que puedes obtener 
vía simulación). ¿Cuál es la aproximación más cercana a la verdadera 
distribución?

Pista: $se(\hat{\mu}) = 1/\sqrt{n}$

#### Respuesta

En el caso del métodeo delta, recordemos

<div class="caja">
**Método delta**. Si $\tau=g(\theta)$ donde $\theta$ consta de únicamente un 
parámetro, g es diferenciable y $g´(\theta)\neq 0$ entonces
$$\frac{\sqrt{n}(\hat{\tau}-\tau)}{\hat{se}(\hat{\tau})}\leadsto N(0, 1)$$
donde $\hat{\tau}=g(\theta)$ y

$$\hat{se}(\hat{\tau})=|g´(\hat{\theta})|\hat{se}(\hat{\theta})$$
</div>

En este caso tenemos $\theta=\mu$ y $g(\mu)=e^\mu$, por tanto, el estimador de máxima verosimiitud para $e^\mu$ es
$$\hat{\tau}=e^{\bar(X)}.$$

Para calcular el error estándar comencemos calculando $g'(\mu)=e^\mu$ por lo que
$$|g'(\hat{\mu})|=e^{\bar(X)}$$

y usando la pista tenemos 
$$se(\hat{\mu}) = 1/\sqrt{n}$$

por lo tanto,

$$\hat{se}(\hat{\tau})=|g'(\hat{\mu})|se(\hat{\mu})=e^{\bar(X)} \cdot 1/\sqrt{n}$$

Calculamos la muestra y elintervalo:

```{r}
set.seed(123456789)
x <- rnorm(100, mean = 5)

# calculamos x_bar y la media
x_bar <- mean(x)
se_hat <- exp(x_bar) * 1 / sqrt(100)

# Intervalo: tau_hat +- se_hat
exp(x_bar) - 1.96 * se_hat
exp(x_bar) + 1.96 * se_hat

# Bootstrap paramétrico

# Bootstrap no paramétrico
```


2. La base de datos vancouver.csv contiene promedios de precipitación de 
mediciones (en mm) provenientes de Vancouver entre 1960 y 1994.

* Utiliza b-splines cúbicos para estudiar la relación entre el día y el 
promedio registrado. Deberás crear una variable numérica x que represente el día
y utiliza como nudos los extremos y 3 puntos interiores igualmente espaciados, 
es decir, tendrás 4 regiones. Grafica la curva estimada.

* Crea bandas de errores estándar usando bootstrap paramético y suponiendo que 
los errores tienen una distribución normal.

